import type { Metadata } from "next";
import StoreProvider from "@/stores/storeProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/authContext";
import NavigationMenu from "@/components/common/navigationMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ backgroundColor: "white", height: "100%", width: "100%" }}
      >
        <AuthProvider>
          <StoreProvider>
            <NavigationMenu />
            <div className="content">{children}</div>
          </StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
